create table public.messages (
  id bigint generated by default as identity primary key,
  sender_id uuid references auth.users not null,
  recipient_id uuid references auth.users not null,
  content text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.messages enable row level security;

create policy "Users can see their own messages"
on public.messages for select
using ( auth.uid() = sender_id or auth.uid() = recipient_id );

create policy "Users can insert their own messages"
on public.messages for insert
with check ( auth.uid() = sender_id );
